# Site settings
title: Thomas Finch
email: tomf64@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thomasfinch.me" # the base hostname & protocol for your site
twitter_username: tomf64
github_username:  thomasfinch

# Build settings
markdown: redcarpet